# Generated by Django 4.0.5 on 2022-06-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='FollowersCount',
        ),
    ]
